# Reference: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
service: default
runtime: nodejs20
instance_class: F2

env_variables:
  # USER_SESSIONS_STORAGE_PATH: default
  # APP_PROPERTIES_PATHS: properties
  # BBVA_ENV: {{ env }}


handlers:
  - url: /index.html
    script: auto
    secure: always
    # http_headers:
    #   Access-Control-Allow-Origin: '*'
  - url: /(.*\.(html|js|css|svg|json|png|jpg|gif|map|woff|woff2|ttf|ico))$
    static_files: public/\1
    upload: public/.*\.(html|js|css|svg|json|png|jpg|gif|map|woff|woff2|ttf|ico)
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /.*
    script: auto
    secure: always
    # http_headers:
    #   Access-Control-Allow-Origin: '*'
