# # Reference: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
# service: default
# runtime: nodejs20
# # instance_class: F2

# env_variables:
#   USER_SESSIONS_STORAGE_PATH: default
#   APP_PROPERTIES_PATHS: properties
#   # BBVA_ENV: {{ env }}


# handlers:
#   - url: /index.html
#     script: auto
#     secure: always

#   - url: /(.*\.(html|js|css|svg|json|png|jpg|gif|map|woff|ttf|ico))$
#     static_files: public/\1
#     upload: public/.*\.(html|js|css|svg|json|png|jpg|gif|map|woff|ttf|ico)
#     secure: always
#     login: required

#   - url: /.*
#     script: auto
#     secure: always
# app.yaml
runtime: custom
env: flex
# If you have one application, please use "default" for service
service: default
# VPC Network if you have one
#network:
#  name: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 15
