steps:
# - name: node:20
#   entrypoint: npm
#   args: ["install", "--registry https://registry.npmjs.org"]
# - name: node:20
#   entrypoint: npm
#   args: ["run", "build"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'echo "Ejecutando mi script personalizado..." && ./webapp/startup.sh --cache-from gcr.io/google.com/cloudsdktool/cloud-sdk']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --cache-from gcr.io/google.com/cloudsdktool/cloud-sdk']
timeout: '1600s'