# steps:
# # - name: node:20
# #   entrypoint: npm
# #   args: ["install", "--registry https://registry.npmjs.org"]
# # - name: node:20
# #   entrypoint: npm
# #   args: ["run", "build"]
# # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
# #   entrypoint: 'bash'
# #   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
# timeout: '1600s'
steps:
#Create .env file from Google Cloud Build substitution variables
# - name: node
#   entrypoint: npm
#   args: ["run", "create-env"]
#   env:
#     - 'VUE_APP_APP_NAME=${_VUE_APP_APP_NAME}'
#     - 'VUE_APP_BASE_API_URL=${_VUE_APP_BASE_API_URL}'
#     - 'VUE_APP_OTHER_SECRET=${_VUE_APP_OTHER_SECRET}'
#The .env file is prepared and ready to deploy to Google App Engine
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"